# Generated by Django 2.2 on 2020-07-14 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='admission_no',
            field=models.CharField(default='12345', max_length=50),
        ),
    ]
