# Generated by Django 2.2 on 2020-07-14 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_student_admission_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='admission_no',
            field=models.CharField(default='00000', max_length=50),
        ),
    ]
