# Generated by Django 2.2 on 2020-07-15 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_auto_20200715_0933'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='email',
        ),
    ]
