# Generated by Django 2.2 on 2020-07-18 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_remove_school_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='books/pdfs/'),
        ),
    ]
