# Generated by Django 2.2 on 2020-07-18 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0012_student_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='image',
            field=models.ImageField(default='noimage.jpg', upload_to='student_photos'),
        ),
    ]
