# Generated by Django 2.2 on 2020-07-21 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0014_auto_20200718_1011'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('author', models.CharField(max_length=150)),
                ('pdf', models.FileField(blank=True, null=True, upload_to='books/pdfs/')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='books/cover/')),
            ],
        ),
    ]
