# Generated by Django 2.2 on 2020-08-19 14:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('students', '0015_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fac_fname', models.CharField(max_length=150)),
                ('fac_lname', models.CharField(max_length=150)),
                ('mobile_no', models.CharField(max_length=13)),
                ('department', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('faculty_id', models.CharField(default='00000', max_length=50)),
                ('image', models.ImageField(default='default.jpg', upload_to='faculty_photos')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
