# Generated by Django 2.2 on 2020-08-19 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0016_faculty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='faculty_id',
            field=models.CharField(blank=True, default='00000', max_length=50, null=True),
        ),
    ]
