# Generated by Django 2.2 on 2020-07-18 13:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Provide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title1', models.CharField(max_length=250)),
                ('content1', models.TextField()),
                ('title2', models.CharField(max_length=250)),
                ('content2', models.TextField()),
                ('title3', models.CharField(max_length=250)),
                ('content3', models.TextField()),
                ('title4', models.CharField(max_length=250)),
                ('content4', models.TextField()),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('icon1', models.ImageField(blank=True, null=True, upload_to='icons')),
                ('icon2', models.ImageField(blank=True, null=True, upload_to='icons')),
                ('icon3', models.ImageField(blank=True, null=True, upload_to='icons')),
                ('icon4', models.ImageField(blank=True, null=True, upload_to='icons')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
