# Generated by Django 2.2 on 2020-07-21 03:39

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website', '0002_provide'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Home1',
            new_name='Homepage',
        ),
        migrations.DeleteModel(
            name='Provide',
        ),
    ]
