# Generated by Django 3.1 on 2020-11-03 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0003_auto_20201022_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='expense_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
