# Generated by Django 3.1 on 2020-11-03 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0004_expense_expense_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='expense_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
